name: Release

on:
  workflow_dispatch:

permissions:
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: write
  packages: write

jobs:
  release:

    runs-on: ubuntu-latest
    permissions: write-all
    
    steps:
    - name: Install GitVersion
    - uses: actions/setup-gitversion@v1.0.0
      with:
        gitversion-version: 5.1.1
    - run: GitVersion
        
    - name: Check out the repo
      uses: actions/checkout@v4
    - name: Git Config
      run: |
        git config --global user.email "admin@cludus.xyz"
        git config --global user.name "cludusadmin"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
            
    - name: Build and push Docker images
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: .
        push: true
        tags: |
          ghcr.io/cludus/gateway-dotnet:${{steps.gitversion.outputs.majorMinorPatch}}
          ghcr.io/cludus/gateway-dotnet:latest


# ${{steps.gitversion.outputs.majorMinorPatch}}


#    - name: Create Github Release
#      id: create_release
#     uses: actions/create-release@v1
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        tag_name: ${{ github.ref }}
#        release_name: Release ${{ github.ref }}
#        body: |
#          Version ${{ steps.version.outputs.release_tag }}
#        draft: false
#        prerelease: false
